### ISSUE TITLE
判断一个bitmap 是否包含另外一个 返回true 或者false

### ISSUE THREAD

**Issue by lizhanyang505** [lihuigang/hive-bitmap-udf#11]
比如
id: 00101, 00010, 10000, 30001
把上面的所有的id 放入到一个bitmap， 然后基于生成的bitmap 判断 是否包含 00101 这个独有的bitmap，或者00101, 00010 生成的bitmap

**Comment by lihuigang** [comment]
是需要判断一个bitmap是否包含另一个bitmap的全部元素吗？

**Comment by lizhanyang505** [comment]
是的， 没有见到这个函数。可能两个元素的添加顺序不同。但是只要全部包含就返回true

**Comment by lihuigang** [comment]
增加了一个 bitmap_contains udf，使用方式：
1、bitmap_contains(bitmap,num)
2、bitmap_countains(bitmap1,bitmap2)
