### ISSUE TITLE
交、并、差不生效

### ISSUE THREAD

**Issue by li-dinghao** [lihuigang/hive-bitmap-udf#16]
to_bitmap，bitmap_union，bitmap_count 这几个没问题，但bitmap_and、bitmap_or、bitmap_xor 这几个的结果和第二个参数是一样的。

**Comment by lihuigang** [comment]
使用这个jar包试下？https://github.com/lihuigang/hive-bitmap-udf/releases/download/v1.0.4/hive-bitmap-udf.jar
![image](https://github.com/lihuigang/hive-bitmap-udf/assets/35155212/732a6679-c06b-4950-ae7f-f92013d762a9)
![image](https://github.com/lihuigang/hive-bitmap-udf/assets/35155212/d28cd0e4-14ce-45c3-a9d4-37a3ea93c493)
![image](https://github.com/lihuigang/hive-bitmap-udf/assets/35155212/9a7273cf-9369-4974-986f-85b62239e1e5)

**Comment by li-dinghao** [comment]
这个能否在Hive 2.1.0 版本下使用？

**Comment by lihuigang** [comment]
可以

**Comment by li-dinghao** [comment]
<img width="596" alt="Snipaste_2024-07-08_16-31-17" src="https://github.com/lihuigang/hive-bitmap-udf/assets/70947865/444d4147-1980-4d9f-97d4-06b84232a170"> 这是对bitmap求count后的结果。
还是同样的问题，交、并、差的结果与第二个参数一样。我是在maxcompute下使用，而MaxCompute兼容的Hive版本为2.1.0，对应Hadoop版本为2.7.2，我将依赖改成了 hive 2.1.0。

**Comment by lihuigang** [comment]
我的微信:wx-asdfg0104
微信交流下？
