### ISSUE TITLE
bitmap_and结果与预期不符

### ISSUE THREAD

**Issue by laymanxiayb** [lihuigang/hive-bitmap-udf#4]
我在hive上执行，结果与预期不符，具体如下：
select udf.bitmap_count(udf.bitmap_and(udf.to_bitmap(1), udf.to_bitmap(2)));  -- 预期0，结果返回1
select udf.bitmap_count(udf.bitmap_or(udf.to_bitmap(1), udf.to_bitmap(2)));     -- 预期2，结果返回1

是有什么需要注意的地方吗？

**Comment by laymanxiayb** [comment]
是不是roaringbitmap版本过低？看网上说0.9.7版本有修复这个问题

**Comment by lihuigang** [comment]
已修复，代码逻辑问题

**Comment by laymanxiayb** [comment]
您的邮件我已收到，我会尽快回复！

**Comment by lihuigang** [comment]
已解决
